// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emllqryfmvznogatvgte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtbGxxcnlmbXZ6bm9nYXR2Z3RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MDk1MjQsImV4cCI6MjA2NTk4NTUyNH0.WuWvonP9CNbZQSqGAu8o6ShOqByePJ_qZhPS2ILCjFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);